### ISSUE TITLE
could not find cpp_functions.so - please reinstall

### ISSUE THREAD

**Issue by aiqubo** [aresti/primalscheme#10]
"could not find cpp_functions.so - please reinstall"

cloud you help me for how to fix this error?

**Comment by aresti** [comment]
Hi, could I get a bit more info on your environment so I can try to assist? How did you install the package, and what is your OS?

**Comment by aiqubo** [comment]
my system is centos 7.5, and i install use command  as follow
"""git clone https://github.com/aresti/primalscheme.git
cd primalscheme
virtualenv -p python3 venv
source venv/bin/activate
pip3 install .
“”“

**Comment by aresti** [comment]
I think your issue is the installation of the porechop dependency. We are working to remove this in the next release. In the mean time I managed to get it working in a fresh CentOS 7 install by doing the following:

install GCC 8 from developer toolset by doing the following:
`yum install centos-release-scl`
`yum install devtoolset-8-gcc devtoolset-8-gcc-c++`

then make DTS the default:
`source scl_source enable devtoolset-8`

finally add to bashrc:
`scl enable devtoolset-8 -- bash`

And then `pip install .` worked for me from within the primalscheme directory, (with the virtualenv active)

Let me know how you get on.

**Comment by aresti** [comment]
Also, if you haven't already you might to do:
`yum install python36-devel`

to ensure that Python.h header is available to the compiler

**Comment by aiqubo** [comment]
work now, thank you very much
